version: 1
accounts:
- name: alice
  coins:
  - 2000000000tpt
- name: bob
  coins:
  - 1000000000tpt
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 10000000tpt
validators:
- name: alice
  bonded: 100000000tpt
